(part "LF353P"
    (packageRef "DIP794W53P254L959H508Q8N")
    (interface
        (port "1" (symbPinId 1) (portName "1OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "1IN-") (portType INOUT))
        (port "3" (symbPinId 3) (portName "1IN+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VCC-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "2IN+") (portType INOUT))
        (port "6" (symbPinId 6) (portName "2IN-") (portType INOUT))
        (port "7" (symbPinId 7) (portName "2OUT") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-LF353P")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LF353P?qs=EIjG%252BN7kn%252BnHJN43AgArjw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LF353P")
    (property "Description" "Dual General-Purpose JFET-input Operational Amplifier")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/lf353.pdf")
    (property "symbolName1" "LF353P")
)
